### ISSUE TITLE
LobbySystem

### ISSUE THREAD

**Issue by xXMcpeGamerXx03** [LucDevOffical/BetterLobby#1]
Wo ist das denn ein better LobbySystem?

**Comment by LucDevOffical** [comment]
Es wird aktuell noch entwickelt. Willst du eigentlich nur rum meckern?

**Comment by xXMcpeGamerXx03** [comment]
Wahrscheinlich wird 14 Tage dran entwickelt und bis jetzt ist noch nichts da außer paar 2 Events und 1 Main Datei. Lost

**Comment by LucDevOffical** [comment]
> Wahrscheinlich wird 14 Tage dran entwickelt und bis jetzt ist noch nichts da außer paar 2 Events und 1 Main Datei. Lost
Ich arbeite auch noch für andere Server 😂 zudem habe ich ein eigenes Netzwerk. Du wirkst mir ehrlich zu kindisch. Die Debatte ist hier beendet!
